window.GERMAN_DATA = {
  "lesson": "B1 – Urlaub: Meer und mehr…",
  "vocab": [
    {"de":"der Urlaub","hu":"nyaralás, szabadság","cat":"Utazás"},
    {"de":"das Urlaubsziel","hu":"úticél, nyaralási cél","cat":"Utazás"},
    {"de":"reisen","hu":"utazni","cat":"Utazás"},
    {"de":"fahren","hu":"utazni, menni járművel","cat":"Utazás"},
    {"de":"fliegen","hu":"repülni","cat":"Utazás"},
    {"de":"ans Meer","hu":"a tengerhez","cat":"Úti célok"},
    {"de":"in die Berge","hu":"a hegyekbe","cat":"Úti célok"},
    {"de":"aufs Land","hu":"vidékre","cat":"Úti célok"},
    {"de":"auf die Insel","hu":"a szigetre","cat":"Úti célok"},
    {"de":"in die Stadt","hu":"a városba","cat":"Úti célok"},
    {"de":"nach Frankreich","hu":"Franciaországba","cat":"Úti célok"},
    {"de":"nach Spanien","hu":"Spanyolországba","cat":"Úti célok"},
    {"de":"nach Portugal","hu":"Portugáliába","cat":"Úti célok"},
    {"de":"nach Italien","hu":"Olaszországba","cat":"Úti célok"},
    {"de":"nach Deutschland","hu":"Németországba","cat":"Úti célok"},
    {"de":"nach Rom","hu":"Rómába","cat":"Úti célok"},
    {"de":"an die Adria","hu":"az Adriára / az Adriai-tengerhez","cat":"Úti célok"},
    {"de":"an den Gardasee","hu":"a Garda-tóhoz","cat":"Úti célok"},
    {"de":"in die Alpen","hu":"az Alpokba","cat":"Úti célok"},
    {"de":"in die USA","hu":"az USA-ba","cat":"Úti célok"},
    {"de":"auf die Malediven","hu":"a Maldív-szigetekre","cat":"Úti célok"},
    {"de":"die Sehenswürdigkeit","hu":"nevezetesség","cat":"Város és látnivalók"},
    {"de":"die Altstadt","hu":"óváros","cat":"Város és látnivalók"},
    {"de":"der Dom","hu":"dóm, székesegyház","cat":"Város és látnivalók"},
    {"de":"die Kirche","hu":"templom","cat":"Város és látnivalók"},
    {"de":"das Schloss","hu":"kastély","cat":"Város és látnivalók"},
    {"de":"der Turm","hu":"torony","cat":"Város és látnivalók"},
    {"de":"der Strand","hu":"strand, tengerpart","cat":"Város és látnivalók"},
    {"de":"schwimmen","hu":"úszni","cat":"Tevékenységek"},
    {"de":"tauchen","hu":"búvárkodni","cat":"Tevékenységek"},
    {"de":"wandern","hu":"túrázni","cat":"Tevékenységek"},
    {"de":"Ski fahren","hu":"síelni","cat":"Tevékenységek"},
    {"de":"Rad fahren","hu":"kerékpározni","cat":"Tevékenységek"},
    {"de":"sich sonnen","hu":"napozni","cat":"Tevékenységek"},
    {"de":"sich ausruhen","hu":"pihenni","cat":"Tevékenységek"},
    {"de":"faulenzen","hu":"lustálkodni","cat":"Tevékenységek"},
    {"de":"lesen","hu":"olvasni","cat":"Tevékenységek"},
    {"de":"Deutsch lernen","hu":"németet tanulni","cat":"Tevékenységek"},
    {"de":"Leute kennenlernen","hu":"embereket megismerni","cat":"Tevékenységek"},
    {"de":"Sehenswürdigkeiten besichtigen","hu":"nevezetességeket megtekinteni","cat":"Tevékenységek"},
    {"de":"Fotos machen","hu":"fényképeket készíteni","cat":"Tevékenységek"},
    {"de":"einen Ausflug machen","hu":"kirándulást tenni","cat":"Tevékenységek"},
    {"de":"ein Museum besuchen","hu":"múzeumot meglátogatni","cat":"Tevékenységek"},
    {"de":"eine Stadtrundfahrt machen","hu":"városnéző körutat tenni","cat":"Tevékenységek"},
    {"de":"ins Theater gehen","hu":"színházba menni","cat":"Tevékenységek"},
    {"de":"in die Oper gehen","hu":"operába menni","cat":"Tevékenységek"},
    {"de":"ins Restaurant gehen","hu":"étterembe menni","cat":"Tevékenységek"},
    {"de":"das Surfbrett","hu":"szörfdeszka","cat":"Felszerelés"},
    {"de":"das Deutschbuch","hu":"németkönyv","cat":"Felszerelés"},
    {"de":"die Badehose","hu":"férfi fürdőnadrág","cat":"Felszerelés"},
    {"de":"die Skier","hu":"sílécek","cat":"Felszerelés"},
    {"de":"der Anorak","hu":"anorák","cat":"Felszerelés"},
    {"de":"die Taucherbrille","hu":"búvárszemüveg","cat":"Felszerelés"},
    {"de":"der Fotoapparat","hu":"fényképezőgép","cat":"Felszerelés"},
    {"de":"die Wanderschuhe","hu":"túracipő","cat":"Felszerelés"},
    {"de":"der Bikini","hu":"bikini","cat":"Felszerelés"},
    {"de":"der Regenschirm","hu":"esernyő","cat":"Felszerelés"},
    {"de":"die Sonnenbrille","hu":"napszemüveg","cat":"Felszerelés"},
    {"de":"die Sonnencreme","hu":"naptej","cat":"Felszerelés"},
    {"de":"die Regenjacke","hu":"esőkabát","cat":"Felszerelés"},
    {"de":"der Reiseführer","hu":"útikönyv / idegenvezető","cat":"Felszerelés"},
    {"de":"Ich glaube, dass ...","hu":"Azt hiszem, hogy ...","cat":"Hasznos mondatok"},
    {"de":"Ich finde, dass ...","hu":"Úgy gondolom, hogy ...","cat":"Hasznos mondatok"},
    {"de":"Wenn es regnet, ...","hu":"Ha esik az eső, ...","cat":"Hasznos mondatok"},
    {"de":"Ich habe ... gemacht.","hu":"...-t csináltam.","cat":"Perfekt"},
    {"de":"Ich bin ... gefahren.","hu":"...-ba/-be utaztam.","cat":"Perfekt"},
    {"de":"Ich bin ... geflogen.","hu":"...-ba/-be repültem.","cat":"Perfekt"}
  ],
  "quiz": [
    {"type":"mc","q":"Mit jelent: die Sehenswürdigkeit?","opts":["szállás","nevezetesség","útlevél"],"a":1},
    {"type":"mc","q":"Mit jelent: wandern?","opts":["túrázni","úszni","foglalni"],"a":0},
    {"type":"mc","q":"Melyik helyes? ___ Italien","opts":["nach","in","an","auf"],"a":0},
    {"type":"mc","q":"Melyik helyes? ___ die Alpen","opts":["nach","in","an","auf"],"a":1},
    {"type":"mc","q":"Melyik helyes? ___ Meer","opts":["nach","ins","ans","aufs"],"a":2},
    {"type":"mc","q":"Melyik helyes Perfekt? Ich ___ nach Rom ___.","opts":["habe / geflogen","bin / geflogen","bin / gefliegt"],"a":1},
    {"type":"mc","q":"Melyik helyes Perfekt? Wir ___ ein Museum ___.","opts":["haben / besucht","sind / besucht","haben / besuchen"],"a":0},
    {"type":"mc","q":"Melyik a helyes dass-mondat?","opts":["Ich glaube, dass Urlaub ist wichtig.","Ich glaube, dass Urlaub wichtig ist.","Ich glaube, dass ist Urlaub wichtig."],"a":1},
    {"type":"text","q":"Fordítsd németre: A tengerhez szeretnék utazni.","answers":["ich möchte ans meer fahren","ich mochte ans meer fahren"]},
    {"type":"text","q":"Fordítsd németre: Azt hiszem, hogy a nyaralás fontos.","answers":["ich glaube, dass urlaub wichtig ist"]}
  ]
};
