window.GERMAN_DATA = {
  "lesson": "B1 – Urlaub: Meer und mehr…",
  "vocab": [
    {"de":"der Urlaub","hu":"nyaralás, szabadság","cat":"Utazás","example":"Im Sommer mache ich zwei Wochen Urlaub.","example_hu":"Nyáron két hét szabadságot veszek ki."},
    {"de":"das Urlaubsziel","hu":"úticél, nyaralási cél","cat":"Utazás","example":"Unser Urlaubsziel ist dieses Jahr Italien.","example_hu":"Idén Olaszország az úti célunk."},
    {"de":"reisen","hu":"utazni","cat":"Utazás","example":"Ich reise gern mit dem Zug durch Europa.","example_hu":"Szívesen utazom vonattal Európában."},
    {"de":"fahren","hu":"utazni, menni járművel","cat":"Utazás","example":"Wir fahren morgen mit dem Auto nach Wien.","example_hu":"Holnap autóval Bécsbe utazunk."},
    {"de":"fliegen","hu":"repülni","cat":"Utazás","example":"Nächste Woche fliege ich nach Spanien.","example_hu":"Jövő héten Spanyolországba repülök."},
    {"de":"ans Meer","hu":"a tengerhez","cat":"Úti célok","example":"Im August fahren wir ans Meer.","example_hu":"Augusztusban a tengerhez utazunk."},
    {"de":"in die Berge","hu":"a hegyekbe","cat":"Úti célok","example":"Im Winter fahren wir oft in die Berge.","example_hu":"Télen gyakran a hegyekbe utazunk."},
    {"de":"aufs Land","hu":"vidékre","cat":"Úti célok","example":"Am Wochenende fahren wir aufs Land.","example_hu":"Hétvégén vidékre utazunk."},
    {"de":"auf die Insel","hu":"a szigetre","cat":"Úti célok","example":"Morgen fahren wir mit der Fähre auf die Insel.","example_hu":"Holnap komppal megyünk a szigetre."},
    {"de":"in die Stadt","hu":"a városba","cat":"Úti célok","example":"Am Nachmittag gehen wir in die Stadt.","example_hu":"Délután bemegyünk a városba."},
    {"de":"nach Frankreich","hu":"Franciaországba","cat":"Úti célok","example":"Im Frühling reisen wir nach Frankreich.","example_hu":"Tavasszal Franciaországba utazunk."},
    {"de":"nach Spanien","hu":"Spanyolországba","cat":"Úti célok","example":"Sie fliegt im Juli nach Spanien.","example_hu":"Júliusban Spanyolországba repül."},
    {"de":"nach Portugal","hu":"Portugáliába","cat":"Úti célok","example":"Wir möchten nächstes Jahr nach Portugal fahren.","example_hu":"Jövőre Portugáliába szeretnénk utazni."},
    {"de":"nach Italien","hu":"Olaszországba","cat":"Úti célok","example":"Meine Familie fährt jeden Sommer nach Italien.","example_hu":"A családom minden nyáron Olaszországba utazik."},
    {"de":"nach Deutschland","hu":"Németországba","cat":"Úti célok","example":"Ich fahre nächste Woche nach Deutschland.","example_hu":"Jövő héten Németországba utazom."},
    {"de":"nach Rom","hu":"Rómába","cat":"Úti célok","example":"Wir fliegen am Freitag nach Rom.","example_hu":"Pénteken Rómába repülünk."},
    {"de":"an die Adria","hu":"az Adriára / az Adriai-tengerhez","cat":"Úti célok","example":"Viele Ungarn fahren im Sommer an die Adria.","example_hu":"Sok magyar nyáron az Adriára utazik."},
    {"de":"an den Gardasee","hu":"a Garda-tóhoz","cat":"Úti célok","example":"Im Mai fahren wir an den Gardasee.","example_hu":"Májusban a Garda-tóhoz utazunk."},
    {"de":"in die Alpen","hu":"az Alpokba","cat":"Úti célok","example":"Zum Skifahren fahren wir in die Alpen.","example_hu":"Síelni az Alpokba utazunk."},
    {"de":"in die USA","hu":"az USA-ba","cat":"Úti célok","example":"Mein Bruder fliegt morgen in die USA.","example_hu":"A bátyám/öcsém holnap az USA-ba repül."},
    {"de":"auf die Malediven","hu":"a Maldív-szigetekre","cat":"Úti célok","example":"Sie möchten auf die Malediven fliegen.","example_hu":"A Maldív-szigetekre szeretnének repülni."},
    {"de":"die Sehenswürdigkeit","hu":"nevezetesség","cat":"Város és látnivalók","example":"Der Dom ist eine bekannte Sehenswürdigkeit der Stadt.","example_hu":"A dóm a város egyik ismert nevezetessége."},
    {"de":"die Altstadt","hu":"óváros","cat":"Város és látnivalók","example":"Am Abend spazieren wir durch die Altstadt.","example_hu":"Este az óvárosban sétálunk."},
    {"de":"der Dom","hu":"dóm, székesegyház","cat":"Város és látnivalók","example":"Wir besichtigen heute den Dom.","example_hu":"Ma megnézzük a dómot."},
    {"de":"die Kirche","hu":"templom","cat":"Város és látnivalók","example":"Neben dem Hotel steht eine alte Kirche.","example_hu":"A szálloda mellett áll egy régi templom."},
    {"de":"das Schloss","hu":"kastély","cat":"Város és látnivalók","example":"Das Schloss ist über 300 Jahre alt.","example_hu":"A kastély több mint 300 éves."},
    {"de":"der Turm","hu":"torony","cat":"Város és látnivalók","example":"Vom Turm hat man eine schöne Aussicht.","example_hu":"A toronyból szép a kilátás."},
    {"de":"der Strand","hu":"strand, tengerpart","cat":"Város és látnivalók","example":"Am Nachmittag liegen wir am Strand.","example_hu":"Délután a strandon fekszünk."},
    {"de":"schwimmen","hu":"úszni","cat":"Tevékenységek","example":"Im Urlaub schwimme ich jeden Morgen im Meer.","example_hu":"Nyaraláskor minden reggel úszom a tengerben."},
    {"de":"tauchen","hu":"búvárkodni","cat":"Tevékenységek","example":"Auf den Malediven kann man sehr gut tauchen.","example_hu":"A Maldív-szigeteken nagyon jól lehet búvárkodni."},
    {"de":"wandern","hu":"túrázni","cat":"Tevékenységek","example":"Am Wochenende wandern wir in den Bergen.","example_hu":"Hétvégén a hegyekben túrázunk."},
    {"de":"Ski fahren","hu":"síelni","cat":"Tevékenységek","example":"Im Januar fahren wir in Österreich Ski.","example_hu":"Januárban Ausztriában síelünk."},
    {"de":"Rad fahren","hu":"kerékpározni","cat":"Tevékenységek","example":"Im Sommer fahre ich gern am See Rad.","example_hu":"Nyáron szívesen kerékpározom a tó mellett."},
    {"de":"sich sonnen","hu":"napozni","cat":"Tevékenységek","example":"Sie sonnt sich gern am Strand.","example_hu":"Szeret napozni a strandon."},
    {"de":"sich ausruhen","hu":"pihenni","cat":"Tevékenységek","example":"Nach der Wanderung ruhen wir uns im Hotel aus.","example_hu":"A túra után a szállodában pihenünk."},
    {"de":"faulenzen","hu":"lustálkodni","cat":"Tevékenységek","example":"Im Urlaub möchte ich einfach nur faulenzen.","example_hu":"Nyaraláskor egyszerűen csak lustálkodni szeretnék."},
    {"de":"lesen","hu":"olvasni","cat":"Tevékenységek","example":"Am Strand lese ich gern ein Buch.","example_hu":"A strandon szívesen olvasok egy könyvet."},
    {"de":"Deutsch lernen","hu":"németet tanulni","cat":"Tevékenységek","example":"Ich lerne jeden Abend eine halbe Stunde Deutsch.","example_hu":"Minden este fél órát tanulok németül."},
    {"de":"Leute kennenlernen","hu":"embereket megismerni","cat":"Tevékenységek","example":"Auf Reisen kann man viele neue Leute kennenlernen.","example_hu":"Utazás közben sok új embert lehet megismerni."},
    {"de":"Sehenswürdigkeiten besichtigen","hu":"nevezetességeket megtekinteni","cat":"Tevékenységek","example":"In Rom möchten wir viele Sehenswürdigkeiten besichtigen.","example_hu":"Rómában sok nevezetességet szeretnénk megnézni."},
    {"de":"Fotos machen","hu":"fényképeket készíteni","cat":"Tevékenységek","example":"Ich mache im Urlaub viele Fotos.","example_hu":"Nyaraláskor sok fényképet készítek."},
    {"de":"einen Ausflug machen","hu":"kirándulást tenni","cat":"Tevékenységek","example":"Morgen machen wir einen Ausflug an den See.","example_hu":"Holnap kirándulást teszünk a tóhoz."},
    {"de":"ein Museum besuchen","hu":"múzeumot meglátogatni","cat":"Tevékenységek","example":"Bei schlechtem Wetter besuchen wir ein Museum.","example_hu":"Rossz időben meglátogatunk egy múzeumot."},
    {"de":"eine Stadtrundfahrt machen","hu":"városnéző körutat tenni","cat":"Tevékenységek","example":"Am ersten Tag machen wir eine Stadtrundfahrt.","example_hu":"Az első napon városnéző körutat teszünk."},
    {"de":"ins Theater gehen","hu":"színházba menni","cat":"Tevékenységek","example":"Heute Abend gehen wir ins Theater.","example_hu":"Ma este színházba megyünk."},
    {"de":"in die Oper gehen","hu":"operába menni","cat":"Tevékenységek","example":"In Wien möchte ich einmal in die Oper gehen.","example_hu":"Bécsben egyszer szeretnék elmenni az operába."},
    {"de":"ins Restaurant gehen","hu":"étterembe menni","cat":"Tevékenységek","example":"Nach der Besichtigung gehen wir ins Restaurant.","example_hu":"A városnézés után étterembe megyünk."},
    {"de":"das Surfbrett","hu":"szörfdeszka","cat":"Felszerelés","example":"Das Surfbrett liegt schon im Auto.","example_hu":"A szörfdeszka már az autóban van."},
    {"de":"das Deutschbuch","hu":"németkönyv","cat":"Felszerelés","example":"Ich nehme mein Deutschbuch mit in den Urlaub.","example_hu":"Magammal viszem a németkönyvemet a nyaralásra."},
    {"de":"die Badehose","hu":"férfi fürdőnadrág","cat":"Felszerelés","example":"Vergiss deine Badehose nicht!","example_hu":"Ne felejtsd el a fürdőnadrágodat!"},
    {"de":"die Skier","hu":"sílécek","cat":"Felszerelés","example":"Die Skier sind auf dem Autodach.","example_hu":"A sílécek az autó tetején vannak."},
    {"de":"der Anorak","hu":"anorák","cat":"Felszerelés","example":"In den Bergen brauche ich einen warmen Anorak.","example_hu":"A hegyekben szükségem van egy meleg anorákra."},
    {"de":"die Taucherbrille","hu":"búvárszemüveg","cat":"Felszerelés","example":"Zum Tauchen brauche ich eine Taucherbrille.","example_hu":"Búvárkodáshoz szükségem van egy búvárszemüvegre."},
    {"de":"der Fotoapparat","hu":"fényképezőgép","cat":"Felszerelés","example":"Ich nehme meinen Fotoapparat auf jede Reise mit.","example_hu":"Minden utazásra magammal viszem a fényképezőgépemet."},
    {"de":"die Wanderschuhe","hu":"túracipő","cat":"Felszerelés","example":"Für die Berge brauche ich gute Wanderschuhe.","example_hu":"A hegyekhez jó túracipőre van szükségem."},
    {"de":"der Bikini","hu":"bikini","cat":"Felszerelés","example":"Sie hat einen neuen Bikini für den Urlaub gekauft.","example_hu":"Új bikinit vett a nyaralásra."},
    {"de":"der Regenschirm","hu":"esernyő","cat":"Felszerelés","example":"Wenn es regnet, brauche ich einen Regenschirm.","example_hu":"Ha esik, szükségem van egy esernyőre."},
    {"de":"die Sonnenbrille","hu":"napszemüveg","cat":"Felszerelés","example":"Bei starkem Sonnenschein trage ich eine Sonnenbrille.","example_hu":"Erős napsütésben napszemüveget viselek."},
    {"de":"die Sonnencreme","hu":"naptej","cat":"Felszerelés","example":"Am Strand benutzen wir immer Sonnencreme.","example_hu":"A strandon mindig használunk naptejet."},
    {"de":"die Regenjacke","hu":"esőkabát","cat":"Felszerelés","example":"Für die Wanderung nehme ich eine Regenjacke mit.","example_hu":"A túrára viszek magammal esőkabátot."},
    {"de":"der Reiseführer","hu":"útikönyv / idegenvezető","cat":"Felszerelés","example":"Im Reiseführer finden wir die wichtigsten Sehenswürdigkeiten.","example_hu":"Az útikönyvben megtaláljuk a legfontosabb nevezetességeket."},
    {"de":"Ich glaube, dass ...","hu":"Azt hiszem, hogy ...","cat":"Hasznos mondatok","example":"Ich glaube, dass Urlaub wichtig ist.","example_hu":"Azt hiszem, hogy a nyaralás fontos."},
    {"de":"Ich finde, dass ...","hu":"Úgy gondolom, hogy ...","cat":"Hasznos mondatok","example":"Ich finde, dass die Altstadt sehr schön ist.","example_hu":"Úgy gondolom, hogy az óváros nagyon szép."},
    {"de":"Wenn es regnet, ...","hu":"Ha esik az eső, ...","cat":"Hasznos mondatok","example":"Wenn es regnet, besuchen wir ein Museum.","example_hu":"Ha esik, meglátogatunk egy múzeumot."},
    {"de":"Ich habe ... gemacht.","hu":"...-t csináltam.","cat":"Perfekt","example":"Ich habe gestern viele Fotos gemacht.","example_hu":"Tegnap sok fényképet készítettem."},
    {"de":"Ich bin ... gefahren.","hu":"...-ba/-be utaztam.","cat":"Perfekt","example":"Ich bin letztes Wochenende nach Wien gefahren.","example_hu":"Múlt hétvégén Bécsbe utaztam."},
    {"de":"Ich bin ... geflogen.","hu":"...-ba/-be repültem.","cat":"Perfekt","example":"Ich bin im Sommer nach Spanien geflogen.","example_hu":"Nyáron Spanyolországba repültem."}
  ],
  "quiz": [
    {"type":"mc","q":"Mit jelent: die Sehenswürdigkeit?","opts":["szállás","nevezetesség","útlevél"],"a":1},
    {"type":"mc","q":"Mit jelent: wandern?","opts":["túrázni","úszni","foglalni"],"a":0},
    {"type":"mc","q":"Melyik helyes? ___ Italien","opts":["nach","in","an","auf"],"a":0},
    {"type":"mc","q":"Melyik helyes? ___ die Alpen","opts":["nach","in","an","auf"],"a":1},
    {"type":"mc","q":"Melyik helyes? ___ Meer","opts":["nach","ins","ans","aufs"],"a":2},
    {"type":"mc","q":"Melyik helyes Perfekt? Ich ___ nach Rom ___.","opts":["habe / geflogen","bin / geflogen","bin / gefliegt"],"a":1},
    {"type":"mc","q":"Melyik helyes Perfekt? Wir ___ ein Museum ___.","opts":["haben / besucht","sind / besucht","haben / besuchen"],"a":0},
    {"type":"mc","q":"Melyik a helyes dass-mondat?","opts":["Ich glaube, dass Urlaub ist wichtig.","Ich glaube, dass Urlaub wichtig ist.","Ich glaube, dass ist Urlaub wichtig."],"a":1},
    {"type":"text","q":"Fordítsd németre: A tengerhez szeretnék utazni.","answers":["ich möchte ans meer fahren","ich mochte ans meer fahren"]},
    {"type":"text","q":"Fordítsd németre: Azt hiszem, hogy a nyaralás fontos.","answers":["ich glaube, dass urlaub wichtig ist"]}
  ]
};
